[project]
name = "crunchbase"
version = "0.1.0"
description = "A Python-based tool for scraping company information from Crunchbase."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
